-- ============================================================
-- InterviewBuddy Database Schema
-- PostgreSQL 16+
--
-- The database itself is created by the deployment layer:
--   * docker-compose: the official postgres image auto-creates it
--     from POSTGRES_DB.
--   * local/dev:        createdb -O interview interviewbuddy
-- (PostgreSQL has no "CREATE DATABASE IF NOT EXISTS" / "USE".)
-- Enum values are stored as VARCHAR + CHECK to stay compatible with the
-- @Enumerated(EnumType.STRING) entity mappings. updated_* columns are
-- maintained by the application (@PreUpdate), not by the database.
-- ============================================================

-- ============================================================
-- AUTH / USERS
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    phone VARCHAR(20),
    college VARCHAR(150),
    branch VARCHAR(100),
    graduation_year INT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    email_verification_expiry TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_role ON users (role);

-- ============================================================
-- CRT MODULE
-- ============================================================

CREATE TABLE crt_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,   -- APTITUDE, REASONING, VERBAL
    display_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crt_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    explanation TEXT,
    concepts TEXT,
    formulas TEXT,
    examples TEXT,
    tips TEXT,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crt_topic_category FOREIGN KEY (category_id) REFERENCES crt_categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_crt_topics_category ON crt_topics (category_id);

CREATE TABLE crt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_option VARCHAR(1) NOT NULL,   -- A, B, C, D
    explanation TEXT,
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crt_question_topic FOREIGN KEY (topic_id) REFERENCES crt_topics(id) ON DELETE CASCADE,
    CONSTRAINT fk_crt_question_category FOREIGN KEY (category_id) REFERENCES crt_categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_crt_questions_topic ON crt_questions (topic_id);
CREATE INDEX idx_crt_questions_category ON crt_questions (category_id);

CREATE TABLE crt_practice_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option VARCHAR(1) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_practice_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_practice_question FOREIGN KEY (question_id) REFERENCES crt_questions(id) ON DELETE CASCADE
);

CREATE INDEX idx_practice_user ON crt_practice_attempts (user_id);
CREATE INDEX idx_practice_question ON crt_practice_attempts (question_id);

CREATE TABLE crt_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    duration_minutes INT NOT NULL,
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    is_published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crt_test_category FOREIGN KEY (category_id) REFERENCES crt_categories(id) ON DELETE CASCADE
);

CREATE TABLE crt_test_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    display_order INT DEFAULT 0,
    CONSTRAINT fk_ctq_test FOREIGN KEY (test_id) REFERENCES crt_tests(id) ON DELETE CASCADE,
    CONSTRAINT fk_ctq_question FOREIGN KEY (question_id) REFERENCES crt_questions(id) ON DELETE CASCADE,
    CONSTRAINT uq_test_question UNIQUE (test_id, question_id)
);

CREATE TABLE crt_test_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMP,
    score INT DEFAULT 0,
    total_questions INT NOT NULL,
    correct_count INT DEFAULT 0,
    incorrect_count INT DEFAULT 0,
    unanswered_count INT DEFAULT 0,
    time_taken_seconds INT,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'SUBMITTED')),
    CONSTRAINT fk_test_attempt_test FOREIGN KEY (test_id) REFERENCES crt_tests(id) ON DELETE CASCADE,
    CONSTRAINT fk_test_attempt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_test_attempt_user ON crt_test_attempts (user_id);

CREATE TABLE crt_test_attempt_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option VARCHAR(1),
    is_correct BOOLEAN,
    CONSTRAINT fk_ctaa_attempt FOREIGN KEY (attempt_id) REFERENCES crt_test_attempts(id) ON DELETE CASCADE,
    CONSTRAINT fk_ctaa_question FOREIGN KEY (question_id) REFERENCES crt_questions(id) ON DELETE CASCADE,
    CONSTRAINT uq_attempt_question UNIQUE (attempt_id, question_id)
);

-- ============================================================
-- CODING MODULE
-- ============================================================

CREATE TABLE coding_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL UNIQUE,
    description VARCHAR(500),
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE coding_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL UNIQUE,
    description VARCHAR(500),
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE coding_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(170) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    constraints_text TEXT,
    difficulty VARCHAR(20) NOT NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    topic VARCHAR(60),
    starter_code TEXT,
    pattern_id BIGINT,
    external_url VARCHAR(500),
    platform VARCHAR(20) NOT NULL DEFAULT 'OTHER' CHECK (platform IN ('LEETCODE', 'CODECHEF', 'CODEFORCES', 'OTHER')),
    is_published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coding_pattern FOREIGN KEY (pattern_id) REFERENCES coding_patterns(id) ON DELETE SET NULL
);

CREATE INDEX idx_coding_difficulty ON coding_problems (difficulty);
CREATE INDEX idx_coding_topic ON coding_problems (topic);
CREATE INDEX idx_coding_pattern ON coding_problems (pattern_id);

-- Many-to-many link between a problem and the sheets it appears in
-- (e.g. a problem can belong to both Neetcode 150 and Blind 75).
CREATE TABLE coding_sheet_problems (
    sheet_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    PRIMARY KEY (sheet_id, problem_id),
    CONSTRAINT fk_csp_sheet FOREIGN KEY (sheet_id) REFERENCES coding_sheets(id) ON DELETE CASCADE,
    CONSTRAINT fk_csp_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE INDEX idx_csp_problem ON coding_sheet_problems (problem_id);

CREATE TABLE coding_examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    input_text TEXT NOT NULL,
    output_text TEXT NOT NULL,
    explanation TEXT,
    display_order INT DEFAULT 0,
    CONSTRAINT fk_example_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE TABLE test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    input_data TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_sample BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT DEFAULT 0,
    CONSTRAINT fk_testcase_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE INDEX idx_testcase_problem ON test_cases (problem_id);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    language VARCHAR(30) NOT NULL,
    source_code TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'WRONG_ANSWER', 'RUNTIME_ERROR', 'COMPILE_ERROR', 'TIME_LIMIT_EXCEEDED')),
    passed_test_cases INT DEFAULT 0,
    total_test_cases INT DEFAULT 0,
    execution_time_ms INT,
    memory_kb INT,
    stdout_snippet TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE INDEX idx_submission_user ON submissions (user_id);
CREATE INDEX idx_submission_problem ON submissions (problem_id);

CREATE TABLE user_solved_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    first_solved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    best_submission_id BIGINT,
    CONSTRAINT fk_solved_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_solved_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_problem UNIQUE (user_id, problem_id)
);

CREATE TABLE user_problem_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED' CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'SOLVED')),
    solved_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_problem FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE,
    CONSTRAINT uq_progress_user_problem UNIQUE (user_id, problem_id)
);

-- ============================================================
-- AI INTERVIEW MODULE
-- ============================================================

CREATE TABLE interview_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(80) NOT NULL,
    interview_type VARCHAR(20) NOT NULL CHECK (interview_type IN ('TECHNICAL', 'HR', 'MIXED')),
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    question_text TEXT NOT NULL,
    model_answer_notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_iq_role_type ON interview_questions (role, interview_type);

CREATE TABLE interview_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role VARCHAR(80) NOT NULL,
    interview_type VARCHAR(20) NOT NULL CHECK (interview_type IN ('TECHNICAL', 'HR', 'MIXED')),
    difficulty VARCHAR(20) NOT NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    total_questions INT NOT NULL,
    topics VARCHAR(500),
    duration_minutes INT,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    overall_score DECIMAL(5,2),
    relevance_score DECIMAL(5,2),
    technical_score DECIMAL(5,2),
    communication_score DECIMAL(5,2),
    clarity_score DECIMAL(5,2),
    summary_feedback TEXT,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_isession_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_isession_user ON interview_sessions (user_id);

CREATE TABLE interview_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    answer_text TEXT,
    display_order INT DEFAULT 0,
    CONSTRAINT fk_ianswer_session FOREIGN KEY (session_id) REFERENCES interview_sessions(id) ON DELETE CASCADE
);

CREATE TABLE interview_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id BIGINT NOT NULL UNIQUE,
    relevance_score DECIMAL(5,2),
    technical_score DECIMAL(5,2),
    communication_score DECIMAL(5,2),
    clarity_score DECIMAL(5,2),
    feedback TEXT,
    improvement_suggestions TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ieval_answer FOREIGN KEY (answer_id) REFERENCES interview_answers(id) ON DELETE CASCADE
);

-- InterviewStreak: one row per user per calendar date on which the user
-- completed the required interview practice activity. The UNIQUE constraint
-- guarantees at most one practice day per date (duplicate/concurrent
-- completions cannot inflate the streak).
CREATE TABLE interview_streak_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    activity_type VARCHAR(20) NOT NULL DEFAULT 'INTERVIEW',
    activity_reference_id BIGINT,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_streak_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_streak_user_date UNIQUE (user_id, activity_date)
);

CREATE INDEX idx_streak_user_date ON interview_streak_activity (user_id, activity_date);

-- ============================================================
-- LEARNING MODULE
-- ============================================================

CREATE TABLE learning_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    display_order INT DEFAULT 0,
    user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_category_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_learning_category_user ON learning_categories (user_id);

CREATE TABLE learning_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    user_id BIGINT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    resource_type VARCHAR(20) NOT NULL CHECK (resource_type IN ('ARTICLE', 'VIDEO', 'COURSE', 'NOTES', 'EXTERNAL_LINK')),
    content_url VARCHAR(500),
    content_body TEXT,
    is_published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resource_category FOREIGN KEY (category_id) REFERENCES learning_categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_resource_category ON learning_resources (category_id);
CREATE INDEX idx_resource_user ON learning_resources (user_id);

CREATE TABLE user_learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    CONSTRAINT fk_ulp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ulp_resource FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_resource UNIQUE (user_id, resource_id)
);

CREATE TABLE study_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    coding_per_week INT NOT NULL DEFAULT 5,
    interviews_per_week INT NOT NULL DEFAULT 1,
    learning_per_week INT NOT NULL DEFAULT 2,
    CONSTRAINT fk_sg_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_study_goals_user UNIQUE (user_id)
);

CREATE TABLE study_plan_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    day_of_week INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    plan_type VARCHAR(20) NOT NULL CHECK (plan_type IN ('CODING', 'INTERVIEW', 'LEARNING', 'CRT', 'OTHER')),
    time VARCHAR(20),
    duration_minutes INT,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_spi_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);